### ISSUE TITLE
Default logotype is missing

### ISSUE THREAD

**Issue by SlicewOw** [Webspell-RM/Webspell-RM-2.0#12]
After my first installations I recognized, that a default logotype is missing:

![image](https://user-images.githubusercontent.com/18439656/56944267-0c8b6480-6b23-11e9-8ca8-9291e0fac2cd.png)

In this folder there is a logotype but the name starts with an underscore?

![image](https://user-images.githubusercontent.com/18439656/56944296-27f66f80-6b23-11e9-9b1d-507179e4d076.png)

**Comment by Webspell-RM** [comment]
I changed that with the logo update

**Comment by SlicewOw** [comment]
Moin,

ich schreibe einfach mal auf Deutsch.

Du hast mit deinem neusten Commit den Ordner "images" im Default Theme gelöscht - war das gewollt? Das in diesem Commit beschriebene Problem ist also noch nicht gelöst.

**Comment by Webspell-RM** [comment]
den habe ich nicht löschen wollen. hatte nur die bilder gelöscht und ein neues hinzugefügt. Jetzt kann ich den ordner nicht mehr updaten. grrr

**Comment by Webspell-RM** [comment]
Ordner ist wieder online mit dem Logo

**Comment by SlicewOw** [comment]
Issue scheint gelöst, du kannst erledigte Probleme/Themen schließen :)
