### ISSUE TITLE
File is missing in root folder which causes an error in console

### ISSUE THREAD

**Issue by SlicewOw** [Webspell-RM/Webspell-RM-2.0#13]
After my first installations I recognized that there is a error in console regarding "getlang.php" which is used in bbcode.js. The file is expected to be located on root-level:

![image](https://user-images.githubusercontent.com/18439656/56944374-61c77600-6b23-11e9-9ae5-a574e6a1bfc1.png)

**Comment by Webspell-RM** [comment]
I'll take getlang.php out of the base.

**Comment by SlicewOw** [comment]
Du hattest die Zeilen lediglich auskommentiert. Ich würde bevorzugen diese direkt zu löschen, wenn keine Absicht darin besteht, diese Zeilen wieder zu reaktivieren.

**Comment by Webspell-RM** [comment]
Ich habe sie nur auskommentiert weil ich nicht weiß ob die getlang.php irgendwo noch verwendet wird.

**Comment by SlicewOw** [comment]
Issue sollte damit gelöst sein: 0d9627d
