### ISSUE TITLE
bbcode.js is duplicated

### ISSUE THREAD

**Issue by SlicewOw** [Webspell-RM/Webspell-RM-2.0#20]
At the moment we have two bbcode.js files:

- /component/js/bbcode.js
- /component/admin/js/bbcode.js

I think this is not necessary, we can use the file from main js folder. If any functions are necessary for admins only, it should be added in an admin.js file or so.

**Comment by Webspell-RM** [comment]
Auf jedem Fall sollten wir nur noch eine Datei verwenden. Wo die bbcode.js noch verwendet wird müsste man mal überprüfen.

**Comment by Webspell-RM** [comment]
ist gefixt
