### ISSUE TITLE
Add verification if HP URL has a slash at the end

### ISSUE THREAD

**Issue by SlicewOw** [Webspell-RM/Webspell-RM-2.0#23]
There should be a verification with jQuery/JavaScript if an user add a HP URL in installation. If this URL does not contain a slash at the end, he should get a notice to add this slash.

Maybe this workflow is great: If URL is valide, parse URL and check if last char is a slash. If yes, just do nothing. If no, disable button "continue", show a hint for user but he can enable the button again by clicking "I do not care!".

Needed for <base>! Otherwise your page will be not visible at all (broken links!).

**Comment by Webspell-RM** [comment]
Hört sich gut an und finde es top
